# Generated by Django 3.0.6 on 2020-05-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FTTx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('volokno', models.PositiveIntegerField(verbose_name='Кол-во волокн')),
                ('kN', models.TextField(verbose_name='кН')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('link', models.URLField(verbose_name='Ссылка')),
            ],
        ),
    ]
