# Generated by Django 3.0.6 on 2020-05-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webexample', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fttx',
            options={'verbose_name': 'FTTx', 'verbose_name_plural': 'FTTx'},
        ),
        migrations.AlterField(
            model_name='fttx',
            name='link',
            field=models.URLField(unique=True, verbose_name='Ссылка'),
        ),
    ]
