# Generated by Django 3.0.6 on 2020-05-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webexample', '0002_auto_20200509_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADSS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('volokno', models.PositiveIntegerField(verbose_name='Кол-во волокн')),
                ('kN', models.TextField(verbose_name='кН')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('link', models.URLField(unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Подвесной самонесущий, ADSS',
                'verbose_name_plural': 'Подвесной самонесущий, ADSS',
            },
        ),
    ]
