# Generated by Django 3.0.6 on 2020-05-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webexample', '0003_adss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adss',
            name='link',
            field=models.URLField(verbose_name='Ссылка'),
        ),
    ]
