# Generated by Django 3.0.6 on 2020-05-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webexample', '0004_auto_20200517_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adss',
            name='link',
            field=models.URLField(unique=True, verbose_name='Ссылка'),
        ),
    ]
