# Generated by Django 3.0.6 on 2020-05-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webexample', '0005_auto_20200517_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ognestojkij',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('volokno', models.PositiveIntegerField(verbose_name='Кол-во волокн')),
                ('kN', models.TextField(verbose_name='кН')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('link', models.URLField(unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Огнестойкий',
                'verbose_name_plural': 'Огнестойкий',
            },
        ),
        migrations.CreateModel(
            name='Raspredelitelnyj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('volokno', models.PositiveIntegerField(verbose_name='Кол-во волокн')),
                ('kN', models.TextField(verbose_name='кН')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('link', models.URLField(unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Распределительный',
                'verbose_name_plural': 'Распределительный',
            },
        ),
        migrations.CreateModel(
            name='Tip8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('volokno', models.PositiveIntegerField(verbose_name='Кол-во волокн')),
                ('kN', models.TextField(verbose_name='кН')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('link', models.URLField(unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Подвесной, тип-8',
                'verbose_name_plural': 'Подвесной, тип-8',
            },
        ),
        migrations.CreateModel(
            name='Universalnyj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('volokno', models.PositiveIntegerField(verbose_name='Кол-во волокн')),
                ('kN', models.TextField(verbose_name='кН')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('link', models.URLField(unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Универсальный',
                'verbose_name_plural': 'Универсальный',
            },
        ),
        migrations.CreateModel(
            name='Vgrunt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('volokno', models.PositiveIntegerField(verbose_name='Кол-во волокн')),
                ('kN', models.TextField(verbose_name='кН')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('link', models.URLField(unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'В грунт',
                'verbose_name_plural': 'В грунт',
            },
        ),
        migrations.CreateModel(
            name='Vkanal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('volokno', models.PositiveIntegerField(verbose_name='Кол-во волокн')),
                ('kN', models.TextField(verbose_name='кН')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('link', models.URLField(unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'В канализацию',
                'verbose_name_plural': 'В канализацию',
            },
        ),
    ]
